sudo: required

language: ruby

services:
  - docker

before_install:
  - docker version
  - docker info
  - docker pull postgres:9.3
  - docker pull mysql:5.6
  - docker build .
  - gem install bundler
  - bundle install

before_script:
  - bin/prepare

script:
  - bundle exec rspec

deploy:
  provider: script
	skip_cleanup: true
  script: bin/deploy
  on:
  	branch: eap
