language: ruby
rvm:
  - 2.2.0

env:
  global:
    - "HOST_IP=$(/sbin/ifconfig venet0:0 | grep 'inet addr' | awk -F: '{print $2}' | awk '{print $1}')"
    - "DOCKER_HOST=tcp://$HOST_IP:2375"
    - "SLIRP_PORTS=\"2375 80 443 $(seq -s ' ' $(cat /proc/sys/net/ipv4/ip_local_port_range | awk '{print $1, ($1+30) }'))\""

before_install:
  - echo exit 101 | sudo tee /usr/sbin/policy-rc.d
  - sudo chmod +x /usr/sbin/policy-rc.d

install:
  - sudo apt-get -y update
  - sudo apt-get -y install slirp
  - curl https://get.docker.com/ | sudo sh
  - sudo sudo usermod -aG docker "$USER"
  - git clone git://github.com/cptactionhank/sekexe
  - bundle install

before_script:
  - "sekexe/run 'docker -d -H tcp://0.0.0.0:2375' &"
  - "while ! docker info &> /dev/null ; do sleep 5; done"

script:
  - docker version
  - docker pull java:7
  - bundle exec rspec --format documentation --fail-fast
